mykey = "ambi_keypair"
ami = "ami-0889a44b331db0194"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "petclinic-jenkins-server-secgr-de"
jenkins-server-tag = "Jenkins Server of Petclinic-de"
jenkins-profile = "petclinic-jenkins-server-profile-de"
jenkins-role = "petclinic-jenkins-server-role-de"
